CREATE TABLE users (
    id BINARY(16) PRIMARY KEY,
    username VARCHAR(255),
    pass VARCHAR(255),
    fullname VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)